<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-VDQN2TJ" failures="1" tests="4" name="Test" time="3.892" errors="0" timestamp="2021-08-01T16:08:27 IST">
  <testcase classname="testcases.CreateCustomerTest" name="CreateInvalidSecretKey" time="2.624"/>
  <testcase classname="testcases.CreateCustomerTest" name="CreateValidSecretKey" time="0.529"/>
  <testcase classname="testcases.CreateCustomerTest" name="CreateValidSecretKey" time="0.552"/>
  <testcase classname="testcases.DeleteCustomerTest" name="DeleteValidCustID" time="0.619">
    <failure type="java.lang.AssertionError" message="invalid status code received expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: invalid status code received expected [200] but found [404]
at testcases.DeleteCustomerTest.DeleteValidCustID(DeleteCustomerTest.java:27)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- DeleteValidCustID -->
  <testcase classname="setup.Base" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="setup.Base" name="@BeforeSuite setUpMethod" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUpMethod -->
</testsuite> <!-- Test -->
